### ISSUE TITLE
你好,还可以正常运行吗?

### ISSUE THREAD

**Issue by qz270777** [Samiya321/VintageVigil#2]
我似乎无法正常的运行.是我的配置文件有问题吗?
这是我的config
```toml
# 消息推送配置文件

[notify]
# 用户名称,用于区分不同配置文件
# 可选项，默认为 "Default User"
user = "Default User"

# Telegram 设置
# Telegram用户ID，与企业微信用户ID至少需要一个
# 可通过给 https://t.me/username_to_id_bot 发一条消息来获取
telegram_chat_ids = ["111111"]
# Telegram 消息发送类型
# 可选项：1代表纯文本，2代表文字+图片分开发送，3代表图文一起发送，默认为3
tg_send_type = 3

# 企业微信设置
# 企业微信用户ID，与Telegram聊天ID至少需要一个
wecom_user_ids = ['LongXiang','LiYanTong']
# 企业微信消息发送类型
# 可选项：1代表纯文本，2代表文字+图片分开发送，3代表图文一起发送，默认为3
we_send_type = 3

[common]
# 监控间隔时间（单位：秒）
# 可选项，默认值为 1200秒（20分钟）
delay = 60

# 是否开启价格变动（涨价/降价）提醒
# 可选项，默认值为 true
push_price_changes = true

# 搜索时检索的最大页数
# 可选项，默认值为 20
user_max_pages = 20

# 用于价格转换的汇率（日元到人民币）
# 可选项，默认值为 0.049
exchange_rate = 0.049

# 每个搜索任务的最大并发数，即动态并发搜索的页数
# 可选项，默认值为10
max_concurrency = 10

# 自定义消息推送模板
# 可选项，有默认模板
# 可用占位符如下：
# id 商品ID
# imageURL 商品图片链接
# productName 商品名
# price 商品价格 日元
# priceStatus 商品状态
# priceCurrency 商品价格 人民币
# productURL 商品链接
# site 商品所属平台
# keyword 搜索关键词
msg_tpl = """
【$priceStatus】$productName
【链接】$productURL
【价格】$price 円 == $priceCurrency 元
"""


# 煤炉 网站的搜索设置
[[websites.mercari.searches]]
# 搜索关键字
# 必填项, str
keyword = "呪術廻戦"

# 通知方式
# from * to *
# 必填项
# 第一项 @Samiya310Bot（1），@Lihahadear_bot（2），企业微信Samiya（3）
# 第二项 根据notify中填的ids定
notify = [1,11111]

[websites.mercari.searches.filter]
# 排除关键词，可选项
exclude_keyword = ""
# 卖家ID，可选项
sellerId = ""
# 商品状态，可选项，默认为on_sale和trading
status = ""
# 品类，可选项
categoryId = ""
# 品牌，可选项
brandId = ""
# 最低价格，可选项
price_min = ""
# 最高价格，可选项
price_max = ""
```
这是我的env
```env
# 调试模式
# 如果打开，日志打印为则包含文件名和行号的详细日志格式
 DEBUG=True

# 使用的http客户端类型（aiohttp/httpx）, 默认使用aiohttp
# HTTP_CLIENT = "aiohttp"

# Http代理，用于煤炉 telegram等中国大陆无法访问的接口使用
# HTTP_PROXY="http://127.0.0.1:7890"

# Telegram BotToken
TELEGRAM_BOT_TOKEN_1="****************************************************"
TELEGRAM_BOT_TOKEN_2="****************************************************"

# 企业微信应用的CorpID和CorpSecret
WECOM_CORP_ID=""
WECOM_CORP_SECRET=""
# 企业微信应用的AgentID
WECOM_AGENT_ID_1=""

# 任你购
# 账号名
RENNIGOU_MAIL = ""
# 密码
RENNIGOU_PASS = ""

# Telegram 反代服务器
# 官方接口
# TELEGRAM_API_URL = "https://api.telegram.org/bot{0}/{1}"
# 阿里云新加坡
# TELEGRAM_API_URL = "http://8.222.130.125:8878/bot{0}/{1}"
# Cloudflare反代接口
# TELEGRAM_API_URL = "https://tg.fuuyou.com/bot{0}/{1}"
```
您的tg号似乎无法搜索,怎样联系您?
